name: apt_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - ca-certificates=2025.1.31=hbcca054_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgomp=14.2.0=h77fa898_1
  - liblzma=5.6.4=hb9d3cd8_0
  - liblzma-devel=5.6.4=hb9d3cd8_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libzlib=1.2.13=h4ab18f5_6
  - ncurses=6.5=h2d0b736_3
  - openssl=3.4.0=h7b32b05_1
  - pip=25.0=pyh8b19718_0
  - python=3.9.7=hf930737_3_cpython
  - readline=8.2=h8228510_1
  - setuptools=75.8.0=pyhff2d567_0
  - sqlite=3.46.0=h6d4b2fc_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.45.1=pyhd8ed1ab_1
  - xz=5.6.4=hbcc6ac9_0
  - xz-gpl-tools=5.6.4=hbcc6ac9_0
  - xz-tools=5.6.4=hb9d3cd8_0
  - zlib=1.2.13=h4ab18f5_6
  - pip:
      - accelerate==1.3.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anyio==4.8.0
      - async-timeout==5.0.1
      - attrs==25.1.0
      - backoff==2.2.1
      - backports-tarfile==1.2.0
      - black==25.1.0
      - build==1.2.2.post1
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cohere==4.57
      - colorama==0.4.6
      - contourpy==1.3.0
      - cryptography==44.0.0
      - cycler==0.12.1
      - datasets==2.19.2
      - dill==0.3.8
      - distlib==0.3.9
      - distro==1.9.0
      - docutils==0.21.2
      - exceptiongroup==1.2.2
      - fastavro==1.10.0
      - filelock==3.17.0
      - fonttools==4.55.8
      - frozenlist==1.5.0
      - fsspec==2024.3.1
      - h11==0.14.0
      - hatch==1.14.0
      - hatchling==1.27.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.28.1
      - hyperlink==21.0.0
      - id==1.5.0
      - idna==3.10
      - importlib-metadata==6.11.0
      - importlib-resources==6.5.2
      - isort==6.0.0
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.1.0
      - jeepney==0.8.0
      - jinja2==3.1.5
      - jiter==0.8.2
      - joblib==1.4.2
      - keyring==25.6.0
      - kiwisolver==1.4.7
      - lightgbm==4.3.0
      - lingua-language-detector==2.0.2
      - lxml==5.3.0
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.7.5
      - mdurl==0.1.2
      - more-itertools==10.6.0
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - mypy-extensions==1.0.0
      - networkx==3.2.1
      - nh3==0.2.20
      - nltk==3.8.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.8.61
      - nvidia-nvtx-cu12==12.1.105
      - openai==1.61.1
      - packaging==24.2
      - pandas==2.2.3
      - pathspec==0.12.1
      - pexpect==4.9.0
      - pillow==11.1.0
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - portalocker==3.1.1
      - propcache==0.2.1
      - psutil==6.1.1
      - ptyprocess==0.7.0
      - pyarrow==19.0.0
      - pyarrow-hotfix==0.6
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygments==2.19.1
      - pyparsing==3.2.1
      - pyproject-hooks==1.2.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - pyyaml==6.0.2
      - readme-renderer==44.0
      - regex==2024.11.6
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rfc3986==2.0.0
      - rich==13.9.4
      - sacrebleu==2.4.3
      - safetensors==0.5.2
      - scikit-learn==1.3.2
      - scipy==1.13.1
      - seaborn==0.13.2
      - secretstorage==3.3.3
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - sympy==1.13.3
      - tabulate==0.9.0
      - textdistance==4.6.3
      - threadpoolctl==3.5.0
      - tiktoken==0.7.0
      - tokenizers==0.19.1
      - tomli==2.2.1
      - tomli-w==1.2.0
      - tomlkit==0.13.2
      - torch==2.3.1
      - tqdm==4.66.6
      - transformers==4.41.2
      - triton==2.3.1
      - trove-classifiers==2025.1.15.22
      - twine==6.1.0
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - unilm==0.0.1
      - urllib3==2.3.0
      - userpath==1.9.2
      - uv==0.5.26
      - virtualenv==20.29.1
      - wget==3.2
      - xxhash==3.5.0
      - yarl==1.18.3
      - zipp==3.21.0
      - zstandard==0.23.0
prefix: /fs/nexus-scratch/smksaha/miniconda3/envs/apt_env
